export const dummyData = [
    {
        route:"/dashboard",
        text:"Dashboard"
    },
    {
        route:"/users",
        text:"Users"
    },
    {
        route:"/category",
        text:"Category"
    },
    {
        route:"/products",
        text:"Products"
    },
    {
        route:"/booking",
        text:"Booking"
    },
    {
        route:"/logout",
        text:"Logout"
    }
]